export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const RESET_BUILDER_STATE = "RESET_BUILDER_STATE";
export const RESET_CART_STATE = "RESET_CART_STATE";